### ISSUE TITLE
spell database for evade, gap close, interrupt...etc

### ISSUE THREAD

**Issue by LoggeL** [iLoveSona/GOS#10]
Check not only for the key, but also the spell

e.g.:
spellName == GetCastName(unit, spellSlot) or spellName == spellSlot

Used for Leblanc R, Ziggs W(?),..

Interrupter.lua

**Comment by LoggeL** [comment]
Also questionable (if not specified) Gapclosers:

 ["Elise"] = {_Q, _E},
 ["Lissandra"] = {_E},
 ["LeeSin"] = {_Q},
 ["Malphite"] = {_R},  --can't stop
 ["MasterYi"] = {_Q},  --untargetable
 ["Nocturne"] = {_R},
 ["Olaf"] = {_R},  --????
 ["Pantheon"] = {_R},
 ["Rengar"] = {_R},
 ["Thresh"] = {_Q},
 ["Udyr"] = {_E},
 ["Volibear"] = {_Q},
 ["Vi"] = {_Q},
 ["Zac"] = {_E},
 ["Ziggs"] = {_W},

**Comment by iLoveSona** [comment]
in fact, I think best idea is use cast name for all spell instead qwer...but it's too much work need to do XD

# 

> ["Malphite"] = {_R}, --can't stop

it can't be interrupt, but it should get stun after R end

> ["MasterYi"] = {_Q}, --untargetable

yes, but you can stun him after Q end with some logic
so it would be like: q -> stun -> got deleted instantly 

# 

but as I said, it's hard to test with bot, if you can help me test it would be great

just like I made a mistake yesterday(I thought it would be possible to follow flash with yi's q)

**Comment by LoggeL** [comment]
I used to check in my yi script if it's _Q or _W or _E or _R or spellname
So you only need the names of the special ones

**Comment by iLoveSona** [comment]
but if use structure like yours, there is no way to know the qwer slot for make menu

for ex:

``` lua
["TwistedFate"]     = {"goldcardpreattack"}
["Talon"]       = {_R}
```

we need something like this

``` lua
["TwistedFate"]     = {{["slot"] = _W, ["name"]="goldcardpreattack"}, {["slot"] = _X, ["name"]= "XXXXX"}, ...}
["Talon"]       = {["slot"] = _R}
```

so we can modify very small piece of code

``` lua
--menu
tableList = spellList[GetObjectName(unit)]
for _, table pair(tableList) do
  submenu.addItem(MenuBool.new(GetObjectName(unit).." "..spellText[table.slot+1], true))
end

--OnProcessSpell
tableList = spellList[GetObjectName(unit)]
for _, table pair(tableList) do
  if table.name and spell.name == table.name then callback()
  elseif spell.name == GetCastName(unit, table.slot) then callback()
end
```

**Comment by LoggeL** [comment]
You can't make a menu for TF W only. You have to call it Goldcard or sth, because it's special and has 3 cards.

**Comment by iLoveSona** [comment]
it's another problem, maybe a new field call displayname=gold card is fine

**Comment by LoggeL** [comment]
Yeah I would add a ["specialname"]="goldcard" or sth like that.
If not ["specialname"] then
 spellname=GetCastName(unit, table.slot)
else
 spellname=["specialname"]
end

**Comment by LoggeL** [comment]
Yep and if the field is nil just get GetCastName(unit, table.slot) and use it as displayname

**Comment by iLoveSona** [comment]
ok, seems the last problem is find someone to rework the table XD

**Comment by LoggeL** [comment]
You just need to do it with the special spells. Just give the slot info for the normal ones.

**Comment by LoggeL** [comment]
["Elise"] = {_E},
["Lissandra"] = {_E},
["LeeSin"] = {_Q},
["Nocturne"] = {_R},
["Rengar"] = {_R}, --forget it xD
["Thresh"] = {_Q},
["Vi"] = {_Q},
["Zac"] = {_E},
["Ziggs"] = {_W},

whoops didn't mean to close :S

**Comment by iLoveSona** [comment]
I know it work, but i want keep the code clean...as you can see my pseudo code

**Comment by iLoveSona** [comment]
maybe we should put spells in a database, with multi columns, we can support many feature(evade, gap close, interrupt...etc) 

something like:

| heroName | slot | spellName | cc | channeling |
| --- | --- | --- | --- | --- |
| TwistedFate | W | goldcardpreattack | true | false |
| Katarina | R | nil | false | true |

and generate the table by SQL

**Comment by LoggeL** [comment]
Would require things like width, delay, duration, ...
Lot's of work... I've no free time currently (too much to learn), that's why I quit GoS Dev.

Edit: Make a Spreadsheet list 
https://docs.google.com/spreadsheets/u/0/
and I'll try to contribute in my spare free time :)

**Comment by DarknessVoided** [comment]
Anything i can contribute? Im like having tons of free time next week lmao

**Comment by iLoveSona** [comment]
yes, can you find what data we need for the DB? or you can just start to finish it XD

**Comment by LoggeL** [comment]
Format
Char,Spell,name,dmg,range,range2,delay,width,dmgType,channel,ccType,passive

Example spells ["Tf"]={spell=W3, name="goldcardpreattack", dmg=CalcDmg (...), range (aa range), range2=Nil, delay=aa windup, width=0, dmgType=mixed?,channel=false,ccType="stun",passive=false}

Does this look OK or did I miss something?

**Comment by DarknessVoided** [comment]
@Sona u can lmk what u need me to find or do idk much bout lua but as long as i can learn why not qq lmk

**Comment by iLoveSona** [comment]
@LoggeL not sure, but i think we need this too....
https://github.com/qqwer1/GoS-Lua/blob/master/CCDatabase.lua
or call @qqwer1 for help XD

@DarknessVoided you need to find all data about the spell, you don't need to know lua or sql
just post the column name here like @LoggeL  did in previous comment

**Comment by DarknessVoided** [comment]
Ok. Next monday onwards kek

**Comment by DarknessVoided** [comment]
Noddy ? ._.

**Comment by LoggeL** [comment]
There are many special spells would spell in table => table.ChampName.spell.name for example
spells.TF.W5.name would return the name of W5 for example (goldcardpreattack). TF has 7 parts on W (startRotation, lockBlue-Red, throwBlue-Red)
All camps that have more than 1 spell on one slot should receive a extra entry W1,W2,W3,...

**Comment by qqwer1** [comment]
https://docs.google.com/spreadsheets/d/11t0FDd8YdhBFTOBe-sAQu73rcSGuFn-xkh-5Pv-LZZk/edit?usp=sharing
Edit: now you can also write there

**Comment by iLoveSona** [comment]
@LoggeL I think just use spell name as key is better, like this

| heroName | slot | spellName | cc | channeling |
| --- | --- | --- | --- | --- |
| TwistedFate | W | goldcardpreattack | true | false |
| TwistedFate | W | bluecardpreattack | false | false |
| TwistedFate | W | redcardpreattack | false | false |

because w1, w2, w3 is meanness 

by the way, you put delay time in your table in YI script, do you think we need add that in spell DB too?
https://github.com/LoggeL/GoS/blob/master/MasterYi.lua

**Comment by LoggeL** [comment]
That delay is set up to dodge and has not much to do with the spellcast
We could add duration tho

**Comment by iLoveSona** [comment]
what is duration? it's not spellProc.animationTime from api?

and if i want make a fiora W, vlad W script(like yi Q), i need the "delay" right?

**Comment by DarknessVoided** [comment]
The moment when The ulti burst to get double dmg ;_; just like zed ulti but zed ulti cant dogee i think

**Comment by DarknessVoided** [comment]
Wait lol. For fiora i think she can kek i was thinking about yi xD

**Comment by LoggeL** [comment]
Duration of dot

**Comment by DarknessVoided** [comment]
I think i found a spelldb that is updated to Gnar. Gonna check if the range are fine. Spell name probably still fine.

**Comment by DarknessVoided** [comment]
Ok. So right now reaching Elise. For the W there are 2 modes. One is when elise goes Up and When elise descends

**Comment by DarknessVoided** [comment]
Oh yeah and there's the Spider Ulti which wasn't added in. EliseSpiderR

**Comment by DarknessVoided** [comment]
Fizz jump one and two. So i add in two? Or add in a note?

**Comment by iLoveSona** [comment]
we need all spell based on it's spell name, just like TF has 3 w spell

**Comment by DarknessVoided** [comment]
Uh see eh this. http://pastebin.com/HfEcw4xX LB one kappa

**Comment by iLoveSona** [comment]
yes, 2w, 4r....

**Comment by DarknessVoided** [comment]
Uh ._. Is the speed one correct u reckon?

**Comment by iLoveSona** [comment]
W speed?, it's outdated....w was very fast before

**Comment by DarknessVoided** [comment]
<_< need to find that speed huh ._.

**Comment by LoggeL** [comment]
Check lb changelog :p
Changed from 1600->1300

**Comment by D3ftsu** [comment]
https://github.com/D3ftsu/GoS/blob/master/Common/SpellData.lua

check this ;)

**Comment by iLoveSona** [comment]
ya, like i said, everyone made their own version...gg

**Comment by D3ftsu** [comment]
well we can work together but let's use only one template ..

**Comment by DarknessVoided** [comment]
Oh look deft is here boys

**Comment by iLoveSona** [comment]
well i think @qqwer1 template is best now, or you have better idea?

**Comment by D3ftsu** [comment]
well it's same but without Object name since it's useful for evading.. anyway is it really needed to check buff + CC type ?

**Comment by D3ftsu** [comment]
- ball tracker for orianna is needed, you can get it here : https://github.com/D3ftsu/GoS/blob/master/Common/Orianna.lua#L237-L259

**Comment by iLoveSona** [comment]
not sure, but seems champ name and spell name is enough for most case in evade
https://github.com/Esk0r/LeagueSharp/blob/master/Evade%2FSpellDatabase.cs

and buff+CC type is for anti CC lib

**Comment by D3ftsu** [comment]
well mine is a table for script actually with the same things.. only AOE and CC etc.. are missing is not it ? + ObjectName for Current Skillshot position, for things like impossible to evade and such..

and noddy is just making in the docs i see :^)

**Comment by iLoveSona** [comment]
i'm not talking which one is better, i mean it's better for make the only one spell DB, instead of table everywhere 

btw, we don't need object to know current skillshot position, just calc by ourself

**Comment by D3ftsu** [comment]
i know we can calc it.. but with OnCreateObj we can get the exact position without any calc and such since it's created by the game itself

**Comment by D3ftsu** [comment]
but anyway, i was just talking about the template and what's missing actually, since Noddy didn't make any table for spells yet :^)

**Comment by iLoveSona** [comment]
what? we can generate the lua format table from spellDB

**Comment by D3ftsu** [comment]
well then :p

**Comment by LoggeL** [comment]
Also it's easier to change ;)

**Comment by DarknessVoided** [comment]
Okay I added notes. For some spell that are special.

**Comment by DarknessVoided** [comment]
We might need to change some spell shot that's are new. LIke perhaps Sion which changed skill majorly etc and Fiora etc

**Comment by LoggeL** [comment]
Saw that. You can add a new row, if it's required to have 2 spells for one key.

**Comment by DarknessVoided** [comment]
Alright @LoggeL Anyway https://github.com/Cloudhax23/GoS/blob/master/Spell%20and%20Buff%20stuff Could possibly be added rito?

**Comment by DarknessVoided** [comment]
Its like spell name stuff

**Comment by LoggeL** [comment]
Yeah, everybody could do that :/
I already did so much ;_;

**Comment by DarknessVoided** [comment]
I only did spellname ;-;

**Comment by iLoveSona** [comment]
another spell table
https://github.com/tr33s/LeagueSharp/blob/master/jesuisFiora/SpellBlock.cs#L18-%23L93

https://github.com/DefinitelyRiot/PlatyGOS/blob/master/PActivator.lua#L29
