### ISSUE TITLE
[DLib] GetEnemyHeroes() improve

### ISSUE THREAD

**Issue by iLoveSona** [iLoveSona/GOS#11]
OnObjectLoop test:
run once, check all hero got in one cycle

``` lua
OnLoop(function()
  first = false
end)

OnObjectLoop(function(obj)
  if not first then return end
  PrintChat(hero)
end)
```

**Comment by DarknessVoided** [comment]
Good job bruh <3

**Comment by iLoveSona** [comment]
do you really know what i am try to do?(why github don't support doge face....)

**Comment by DarknessVoided** [comment]
I trying hard to support u kek 😐😐😐😐

**Comment by iLoveSona** [comment]
help me the interrupter table then
https://github.com/iLoveSona/GOS/issues/10

**Comment by DarknessVoided** [comment]
Ok sona ._. I'll list it today kek
